# Generated by Django 5.1.7 on 2025-03-29 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=300, verbose_name='Mavzu nomi')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduResources.classes')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('videoUrl', models.URLField()),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EduResources.lessons')),
            ],
            options={
                'verbose_name': 'Darslik',
                'verbose_name_plural': 'Darsliklar',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quetion', models.TextField()),
                ('option1', models.CharField(max_length=300, verbose_name='Variant 1')),
                ('option2', models.CharField(max_length=300, verbose_name='Variant 2')),
                ('option3', models.CharField(max_length=300, verbose_name='Variant 3')),
                ('option4', models.CharField(max_length=300, verbose_name='Variant 4')),
                ('correct_option', models.PositiveSmallIntegerField(choices=[(1, 'Variant 1'), (2, 'Variant 2'), (3, 'Variant 3'), (4, 'Variant 4')], verbose_name="To'g'ri variant")),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduResources.resources')),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.PositiveSmallIntegerField(choices=[(1, 'Variant 1'), (2, 'Variant 2'), (3, 'Variant 3'), (4, 'Variant 4')], verbose_name='Tanlangan variant')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduResources.test', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
