# Generated by Django 5.1.7 on 2025-03-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduResources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='quetion',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='lessons',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='EduResources.classes'),
        ),
    ]
