# Generated by Django 5.1.7 on 2025-04-01 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduResources', '0003_alter_test_resource_lessons_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='EduResources.lessons'),
        ),
        migrations.CreateModel(
            name='TestStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tests', models.PositiveIntegerField(default=0, verbose_name='Jami testlar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('percentage', models.FloatField(default=0, verbose_name='Test foizi')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduResources.lessons', verbose_name='Mavzu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
