# Generated by Django 5.1.7 on 2025-04-20 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400)),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='type_image')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=170)),
                ('item', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Fizika turi',
                'verbose_name_plural': 'Fizika turlari',
            },
        ),
        migrations.CreateModel(
            name='UserExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_experience_image')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi tajribasi',
                'verbose_name_plural': 'Foydalanuvchi tajribasi',
            },
        ),
        migrations.CreateModel(
            name='WhyUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='whyUs_img')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=180)),
            ],
            options={
                'verbose_name': 'Nima uchun biz',
                'verbose_name_plural': 'Nima uchun biz',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon', models.ImageField(upload_to='social_icons')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='home.contactmodel')),
            ],
        ),
    ]
