# Generated by Django 5.1.7 on 2025-05-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Kontakt xabar', 'verbose_name_plural': 'Kontact xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Kontakt va ijtimoiy tarmoq', 'verbose_name_plural': 'Kontakt va ijtimoiy tarmoqlar'},
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
