# Generated by Django 5.1.7 on 2025-04-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulators',
            name='types',
        ),
        migrations.AddField(
            model_name='simulators',
            name='types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='simulators.simulatortype'),
            preserve_default=False,
        ),
    ]
